server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myProject
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  
mybatis:
  config-location: classpath:mybatis-config.xml



