server: 
  port: 6060

spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/myProject
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa: 
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false
    properties.javax.persistence.validation.mode: none #https://stackoverflow.com/questions/26764532/how-to-disable-hibernate-validation-in-a-spring-boot-project
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  #邮箱配置
  mail: 
    host: smtp.163.com
    username: 16638649445@163.com
    password: zhaoqing1994
    default-encoding: UTF-8
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true
    fromMail: 
      addr: 16638649445@163.com
      
logging:
  config: config/logback-dev.xml
